### ISSUE TITLE
Precedence confusion

### ISSUE THREAD

**Issue by darkpixel** [rc0/mairix#18]
According to the man page: `Individual  command  line  arguments  define separate conditions which are AND-ed together` and `After  the colon, commas delineate separate disjuncts, which are OR-ed together`.

So it would seem that the following command:
`mairix d:20140101- tfc:alice,bob,susan bs:klingons`

...would show any e-mail where alice, bob, OR susan were in the to, from, OR cc fields talking about klingons after 01/01/2014.

I'm getting 0 results even though I have manually identified two messages--one where susan was in the from field and klingons were in the subject after 01/01/2014.

Am I misunderstanding how the precedence and commas work?

**Comment by darkpixel** [comment]
To expound a bit, if I shorten the command to ```mairix d:20140101- tfc:alice,bob,susan``` it does return a few matches, but they are only messages where alice, bob, AND susan are all present in one of the fields.  It appears to be ANDing alice, bob, and susan.

**Comment by vandry** [comment]
A different part of the manpage says:

 * **word1,word2**: This matches if both the words are matched in the specified message part.
 * **word1/word2**: This matches if either of the words are matched in the specified message part.

...which is inconsistent with the section of the manpage which you quoted.

Since the syntax with the commas and slashes does seem to work correctly, it looks like an error in the manpage.
