### ISSUE TITLE
Raise maximum number of mailboxes

### ISSUE THREAD

**Issue by spwhitton** [rc0/mairix#23]
A Debian user has [requested](https://bugs.debian.org/820823) that the limit of 65536 mailboxes be raised.  Is there some reason why a `long` int couldn't be used instead of an `int` for `n_mboxen`?

**Comment by vandry** [comment]
From what I can tell, mairix already assumes extensively that int is 32 bits, so the `int` vs. `long` type isn't the problem or the reason why `n_mboxen` is limited to 65536. In fact, it looks as though the limit might be completely arbitrary and could be easily raised. I am not sure though, so I will have to test it.

**Comment by vandry** [comment]
It wasn't closed. Per the previous comment I believe the limit could be raised but it has to be tested.

**Comment by idallen** [comment]
The number of mailboxes and the number of messages in each mailbox are stored in the same unsigned integer (32 bits), with 16 bits used for each number.  The number of mailboxes is in the upper 16 bits; the number of messages per mailbox is in the lower 16 bits. 

It's not hard to re-proportion the number of bits used for each, i.e. by decreasing the number of mailboxes to increase the number of messages or vice-versa.  You only need to modify encode_mbox_indices() and decode_mbox_indices() in mbox.c.

I did this in an earlier version of mairix, reducing the number of mailboxes to 8 bits and increasing the number of messages to 24 bits.

Of course you have to rebuild all your mairix index files if you do this.

Here's the approximate diff I used for mairix 0.22:
~~~~~
1027c1059,1063
< unsigned int encode_mbox_indices(unsigned int mb, unsigned int msg)/*{{{*/
---
> #define SHIFTBITS 24  /* how many bits to use to count messages */
> #define SHIFTMASKMBS ((1<<(32-SHIFTBITS))-1)
> #define SHIFTMASKMSGS ((1<<SHIFTBITS)-1)
> 
> inline unsigned int encode_mbox_indices(unsigned int mb, unsigned int msg)/*{{{*/
1029,1031c1065
<   unsigned int result;
<   result = ((mb & 0xffff) << 16) | (msg & 0xffff);
<   return result;
---
>   return (mb << SHIFTBITS) | msg;
1034c1068
< void decode_mbox_indices(unsigned int index, unsigned int *mb, unsigned int *msg)/*{{{*/
---
> inline void decode_mbox_indices(unsigned int myindex, unsigned int *mb, unsigned int *msg)/*{{{*/
1036,1037c1070,1071
<   *mb = (index >> 16) & 0xffff;
<   *msg = (index & 0xffff);
---
>   *mb = (myindex >> SHIFTBITS) & SHIFTMASKMBS;
>   *msg = (myindex & SHIFTMASKMSGS);
1044,1045c1078,1080
<   if (db->n_mboxen > 65536) {
<     fprintf(stderr, "Too many mboxes (max 65536, you have %d)\n", db->n_mboxen);
---
>   if (db->n_mboxen >= SHIFTMASKMBS) {
>     fprintf(stderr, "Too many mboxes (max %d, you have %d)\n",
>               SHIFTMASKMBS, db->n_mboxen);
1050,1052c1085,1087
<     if (db->mboxen[i].n_msgs > 65536) {
<       fprintf(stderr, "Too many messages in mbox %s (max 65536, you have %d)\n",
<               db->mboxen[i].path, db->mboxen[i].n_msgs);
---
>     if (db->mboxen[i].n_msgs >= SHIFTMASKMSGS) {
>       fprintf(stderr, "Too many messages in mbox %s (max %d, you have %d)\n",
>               db->mboxen[i].path, SHIFTMASKMSGS, db->mboxen[i].n_msgs);
~~~~~

**Comment by vandry** [comment]
Hi Ian,

Before you work on this change further, I'd like to suggest that squeezing bits sounds like the wrong approach here, and I'd be reluctant to accept that change. Rather than assigning 8 bits to the number of mailboxes and 24 bits to the number of messages, I'd much rather just switch to using a pair of 32-bits fields, or even a 64-bit field for the number of messages. As we would be making an incompatible change to the index file anyway, I would imagine it should not be a problem to grow the size by a tiny bit here.

**Comment by idallen** [comment]
> Before you work on this change further, I'd like to suggest that squeezing bits sounds like the wrong approach here

It is absolutely the wrong approach, but the right approach hasn't been done since this question was posed in 2016, over five years ago.  This wrong approach fixed my problem, and if you adopt the code fragment but change the SHIFTBITS to 16 you get the current behaviour using documented code based on one constant instead of undocumented code using unrelated magic numbers such as 16 and 65536.  It's a temporary fix for people who need it now.

**Comment by vandry** [comment]
6f5531d539540810176ee13c6f07a63e5b21ae37 fixes
