### ISSUE TITLE
Fails when mh folders have an integer for a name

### ISSUE THREAD

**Issue by spwhitton** [rc0/mairix#24]
A Debian user [reports](https://bugs.debian.org/700906) that mairix chokes on mh folders that have an integer for a name.  Such naming doesn't seem to be forbidden by any standard.

**Comment by vandry** [comment]
The user reports this problem about subfolder names. Top-level MH folders with numeric names work fine. 

Actually subfolders with numeric names is kind of problematic for MH because those names collide with the namespace for messages. The error which the user reports is:

'/home/cjr/.claws-mail-mh/Read Mail/2013'

What happens when the 2013th message is inserted into the "Read Mail" folder? Even though this folder is probably not intended to contain any messages (but rather to act just as a containing for subfolders) it could do, and things might break. (A correct implementation could just skip that number and move on to the next one, but then what happens when you want a new subfolder called 2014?)

mairix could probably do its best to support this by stat()ing the file and discovering it's a subfolder not a message.

**Comment by vandry** [comment]
On taking a second look at the code, I believe I can deduce that the user (Claude Rubinson <cjr@grundrisse.org>) must have had a configuration which indexes the "Read Mail" folder (not the "Read Mail/2013" folder) and it thinks that "Read Mail/2013" might be a message inside that folder. In that case, it tries to index it and fails but just writes an error and continues. mairix must have been working despite the warning.

So the correct solution is to avoid adding directories to the list of MH messages. This will require stat'ing messages at scan time, which will slow down scanning unfortunately.

**Comment by spwhitton** [comment]
On Sun, Jul 30, 2017 at 01:36:25PM -0700, Kim Vandry wrote:
> So the correct solution is to avoid adding directories to the list of MH
> messages. This will require stat'ing messages at scan time, which will slow
> down scanning unfortunately.

Perhaps this could be off by default, and configurable?

Maintaining mairix's performance is important if you want to compete
with tools like notmuch.

-- 
Sean Whitton
