### ISSUE TITLE
Broken gzip mbox - Fixup error message

### ISSUE THREAD

**Issue by flohoff** [rc0/mairix#34]
Hi,
when there is a broken gzip mbox the error message is

`failed writing to temp file for /home/flo/Mail/archive/2001/received-200102.gz`

which suggest something out of diskspace or the like. The issue here was a broken/truncated gzip file.

**Comment by vandry** [comment]
I cannot reproduce this. I tried with compressed mbox and compressed Maildir, and with database updates and searching using various output folder types.

grepping for the error message, I see that it can only come from one place in rfc822.c and it does look from reading the code like the error can only come from a genuine temp file write error.

Maybe this can only be triggered by a gzip file that is corrupted in a particular way such that it incorrectly expands to a very large output file and we really do run out of space for the temp file. In which case I would say this bug is unfortuantely wontfix.
